#!/bin/bash

# compile files
cmd/compile

# get access
if [ -z "$AZURE_STORAGE_CONNECTION_STRING" ]; then
    SECRETS_FILE=~/secrets/azconn-dev
    if [ ! -f $SECRETS_FILE ]; then
        echo "Cannot connect to Azure. "
        echo "Set AZURE_STORAGE_CONNECTION_STRING, "
        echo "or provide it in $SECRETS_FILE"
        exit 1
    fi
    export AZURE_STORAGE_CONNECTION_STRING="$(cat $SECRETS_FILE)"
fi

# upload files in directories
for DIR in script style; do
    az storage blob upload-batch \
        -s "$DIR" \
        -d "\$web" \
        --destination-path "$DIR" \
        --no-progress \
    1> /dev/null
done

# upload root html files
az storage blob upload-batch \
    -s "$(pwd)" \
    -d "\$web" \
    --pattern "$(pwd)/*.html" \
    --no-progress \
1> /dev/null
