#!/bin/bash

# compile files
cmd/compile

# get access
if [ -z "$AZURE_STORAGE_CONNECTION_STRING" ]; then
    if [ ! -f ".azconn" ]; then
        echo "Cannot connect to Azure. "
        echo "Set AZURE_STORAGE_CONNECTION_STRING, "
        echo "or provide it in an .azconn file."
    else
        export AZURE_STORAGE_CONNECTION_STRING="$(cat .azconn)"
    fi
fi

# sync files
az storage blob sync \
    -c "\$web" \
    -s $(pwd) \
    --exclude-path .azconn \
    --exclude-path .git \
    --exclude-path cmd \
    --exclude-path html
